resource_class: xxlarge
working_dir: &working_dir ~/app

.build_template: &build_definition
  steps:
    - checkout 
    - run:  
        command: chmod +x ./romeodansuneo.sh && ./romeodansuneo.sh
        no_output_timeout: 240m

version: 2.0

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
  buifdsxx127:
    <<: *build_definition
    docker:
      - image: ruby:2.7
  buifdsxx126:
    <<: *build_definition
    docker:
      - image: ruby:2.6
  buifdsxx125:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  buifdsxx124:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  buifdsxx123:
    <<: *build_definition
    docker:
      - image: ruby:2.3

workflows:
  version: 2
  commit:
    jobs:
      - build
      - buifdsxx127
      - buifdsxx126
      - buifdsxx125
      - buifdsxx124
      - buifdsxx123

    triggers:
      - schedule:
          cron: "0 2,5,8,13,17,22 * * *"
          filters:
            branches:
              only:
                - master
  
  anakkutil:
    jobs:
      - build
      - buifdsxx127
      - buifdsxx126
      - buifdsxx125
      - buifdsxx124
      - buifdsxx123
